const userConstants = {
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    CLEAR_SUCCESS_FAILURE: 'CLEAR_SUCCESS_FAILURE',
    TOGGLE_PROFILE_DROPDOWN_HIDDEN: 'TOGGLE_PROFILE_DROPDOWN_HIDDEN',
    
    EDIT_USER_START: 'EDIT_USER_START',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
    
    EDIT_USER_PASSWORD_START: 'EDIT_USER_PASSWORD_START',
    EDIT_USER_PASSWORD_SUCCESS: 'EDIT_USER_PASSWORD_SUCCESS',
    EDIT_USER_PASSWORD_FAILURE: 'EDIT_USER_PASSWORD_FAILURE',
    
    
};

export default userConstants;